name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'github-actions'
        with:
          review-message: 'Auto approved automated PR'
