name: Continuous Deployment
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

  steps:
    - name: DigitalOcean App Platform deployment
    uses: digitalocean/app_action@main
    with:
      app_name: metis-web
      token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
